Feature/wvqs 50 admin tag delete
arimurashoi2000/newestKita pull request #13
Opened 2023-08-10 06:51 UTC by arimurashoi2000

2023-08-14 09:23 UTC, miokanedaC requested changes
@arimurashoi2000 
seederでエラーがでるので、全見直しお願いします。
class名はキャメルにして、呼び出し元も変えてください。
(エラーが直ったことを確認してからその他のレビューします。)

2023-08-14 09:23 UTC, miokanedaC commented on apps/kita/database/seeders/Admin_userSeeder.php
> +class Admin_userSeeder extends Seeder
クラス名はキャメルでお願いします。

2023-08-14 09:23 UTC, miokanedaC commented on apps/kita/database/seeders/Admin_userSeeder.php
> +        Admin_user::factory()->count(20)->create();
ここらへんも。

2023-08-15 07:01 UTC, miokanedaC requested changes
一旦見れるところ見ました。

以下中心に全体確認お願いします。
- コーディング規約 / インデントの見直し
- 今回対象じゃない機能 / ファイルの削除
- タグ管理周りのエラー解消
- その他コメント参照

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/AdminUserController.php
> +        $admin_user = new AdminUser();
変数にも命名規則があるので、見てくださいね。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Consts/CommonConst.php
> +    const PAGINATION_ADMIN = 3;
すくなって思ったけど、xdがそうなっているんですね。
基本的に20 ~ 30件くらい出しますが、こちらxdに忠実でいいですね。

でも、「3件は流石に少ないんでは？」って思ってみるのも大事です。どういう目的でこの一覧があるかとか考えながら実装してみてくださいね。そして疑問に思ったら聞いてみてくださいね。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/AdminUserController.php
> +                return redirect()->route('admin_users.index')->with('message', '削除処理が削除されました');
削除処理は削除してないんじゃないですかね？

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/routes/web.php
> +use App\Http\Controllers\ProfileController;
こちらは今回の確認から切り離しかと思います。
削除お願いします。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/AdminUserController.php
> +    public function index(Request $request) {
https://docs.google.com/spreadsheets/d/17MfQxuTdDpz9DM9tNFJFKhZ0PFHEw1bul_AkMO5eoF0/edit#gid=1489262498

↑ こちら確認してますか？

PSR2のコーディング規約に沿ってくださいね。
```suggestion
    public function index(Request $request) 
    {
```

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/AdminUserController.php
> +    public function index(Request $request) {
あとインデント確認してください。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/database/seeders/AdminUserSeeder.php
> +        AdminUser::factory()->count(20)->create();
1つテストユーザー作ってあげるのもいいかもですね。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/AdminUserController.php
> +        $escapedEmail = '%' . addcslashes($email, '%_\\') . '%';
ちゃんと考えられていいですね。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/AdminUserController.php
> +            $admin_users->where('last_name', 'like', "%$escapedLastName%");
%で加工必要ってありますか？

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/ArticlesTagController.php
> +use App\Models\Article_tag;
エラーになってます。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/RegisterController.php
> +<?php
これ使ってますか？

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/ArticlesTagController.php
> +use App\Models\Article_tag;
タグ周りはエラー解消してから確認します。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +    }
AuthenticatesUsersをみてみるとlogoutを書き換えるのではなく、loggedOutをoverrideしたらいいんじゃないかなと思うんだけど確認してみてください

<img width="673" alt="Screen Shot 2023-08-15 at 15 17 36" src="https://github.com/arimurashoi2000/newestKita/assets/84494562/9eeff539-d591-40ac-8970-b47294783b97">

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/UserController.php
> +            $users->where('name', 'like', "%$escapedName%");
AdminUserControllerと同じく。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/ProfileController.php
> +<?php
ここには含めないでください。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Http/Middleware/Authenticate.php
> +        if (! $request->expectsJson()|| Request::is('/articles')) {
コメントのところloginしないで書くと管理画面の方いってしまいます。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Models/Article.php
>  namespace App\Models;
これも今回とはかんけないですかね。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/app/Validators/AdminTagValidator.php
> +<?php
これ使ってますか？

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/resources/views/common/pagination.blade.php
> +            <a class="page-link" href="{{ $paginator->nextPageUrl() }}" aria-label="次">
検索結果反映できてないですね。
確認してください。

再現方法：
1. 検索をする
2. 次へを押す

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/resources/views/admin/index.blade.php
> +                                        <th scope="col">メールアドレス</th>
名前がないですかね。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/resources/views/admin/index.blade.php
> +                                            <td>{{$admin_user->last_name}}{{$admin_user->first_name}}</td>
メールアドレスのカラムに別の値が表示されてます。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/resources/views/articles/profile.blade.php
> +<head>
これもこのブランチからけしてください。

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/resources/views/layouts/admin.blade.php
> +<!doctype html>
このファイルはどこでつかってますか？

2023-08-15 07:01 UTC, miokanedaC commented on apps/kita/resources/views/layouts/app.blade.php
> +@if((auth()->guard('admin_users')->check() && !Request::is('admin/login') || Request::is('admin/admin_users/create')))
会員でログインした状態で管理画面でログインすると、articlesのページに管理画面のヘッダーがついてます。

2023-08-16 00:33 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/Admin/RegisterController.php
> +<?php
使用していないので削除しました。

2023-08-16 01:42 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/Admin/AdminUserController.php
> +            $admin_users->where('last_name', 'like', "%$escapedLastName%");
必要ないので修正しました。

2023-08-16 01:44 UTC, arimurashoi2000 commented on apps/kita/resources/views/common/pagination.blade.php
> +            <a class="page-link" href="{{ $paginator->nextPageUrl() }}" aria-label="次">
管理者、会員、タグ一覧画面で修正しました。

2023-08-16 01:45 UTC, arimurashoi2000 commented on apps/kita/resources/views/layouts/admin.blade.php
> +<!doctype html>
初めは使う予定だったのですが、app.blade.phpでヘッダーを分けるようにしたので使用していないです。削除しました。

2023-08-16 03:52 UTC, arimurashoi2000 commented on apps/kita/app/Validators/AdminTagValidator.php
> +<?php
使用していないため削除しました。

2023-08-16 03:53 UTC, arimurashoi2000 commented on apps/kita/resources/views/layouts/app.blade.php
> +@if((auth()->guard('admin_users')->check() && !Request::is('admin/login') || Request::is('admin/admin_users/create')))
条件を修正しました。

2023-08-16 03:53 UTC, arimurashoi2000 commented on apps/kita/app/Http/Middleware/Authenticate.php
> +        if (! $request->expectsJson()|| Request::is('/articles')) {
ミドルウェアを修正しました。

2023-08-16 03:54 UTC, arimurashoi2000 commented on apps/kita/database/seeders/AdminUserSeeder.php
> +        AdminUser::factory()->count(20)->create();
承知しました。
seederで１つだけテストデータを作成するように修正しました。

2023-08-16 04:21 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +    }
承知しました。オーバーライドしたのでお手隙の際に確認をよろしくお願いいたします。

2023-08-17 00:56 UTC, miokanedaC commented on apps/kita/database/seeders/AdminUserSeeder.php
> +        AdminUser::factory()->count(20)->create();
なんで鈴木なのかわからないけどありがとうございます。

次からでいいのですが、レビューを出すときのinstructionとして書いてあげるのいいと思いますよ。

2023-08-17 01:27 UTC, hikaru-yoshimura requested changes
@arimurashoi2000 最後のPRお疲れ様です！
こだわりを持って構築できるようになって欲しいと思うので小言も多いですが、対応お願いします！

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/routes/web.php
>  Route::resource('articles', ArticlesController::class)->only(['index', 'create', 'store', 'edit', 'update', 'show']);
管理者側ではないですが、記事の削除以降のPRが反映されてないですね。
app.blade.phpの修正があったので、軽く全体の動作確認が必要だと思います。確認お願いします。

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/routes/web.php
> +Route::resource('/admin/article_tags', ArticlesTagController::class)->except(['show']);
admin系はすべて/admin/とつくので、以下グルーピングすると、見やすかったりします。
Route::prefix('admin')->group(function () {


あと、ここのPRが最終PRだとすると、21行〜24行はもう不要かもですね。
> Route::get('/', function () {
>     return view('example');
> });
> Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/routes/web.php
>  use App\Http\Controllers\Auth\LoginController;
管理機能じゃないですけど、メンバーをログアウトしたら、記事一覧やログイン画面でもなく`http://localhost/`　に飛ぶので、ユーザはパニック！

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/resources/views/layouts/app.blade.php
> +@endauth
メンバーログイン未実施のユーザーは記事系のヘッダーが消えますね。

これ、デグレって言います。
防ぐには、こういう思考が大事です。
「全体的にユーザーの分岐を変更した」→「バグがあると既存ロジックも影響を受けるから、再テストしよう」→「ユーザーって何種類あるっけ？」→「メンバーログイン/非ログイン　✕　管理者ログイン/非ログイン　の4通りでテストしてみよう」→「あっ、何もログインしてないとヘッダーが出てない！」

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/resources/views/common/pagination.blade.php
> +    @for ($page = $startPage; $page <= $endPage; $page++)
ただのコメントです。修正は不要。
16〜19行がパッと見理解できませんでした。ロジックのコメントは書いた方がいいかもですね。
それか、21行目を@foreachで書き換えれば、1行で書けそうな気もします。

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/resources/views/common/admin_header.blade.php
> +<header>
いいですね。
そういえば、common/header.blade.phpの方は`<header>`タグなかったので、追加お願いします。

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/resources/views/admin/index.blade.php
> +                                <div class="border rounded p-3 text-center custom-bg-lightgray">
ボーダーが丸いのは少しきになりました。「神は細部に宿る」編
会員管理、タグ管理も同様に修正して下さい。
![image](https://github.com/arimurashoi2000/newestKita/assets/108510903/c60c2108-db69-4320-993f-3ef7566e2909)

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/resources/views/admin/index.blade.php
> +                                            <td>{{$adminUser->last_name}}{{$adminUser->first_name}}</td>
デザイン的に間に全角スペース入れてますね。

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/resources/views/admin/index.blade.php
> +                        </div>
検索後に検索条件(性、名、メールアドレス)が消えてますね。
会員管理、タグ管理も同様に修正して下さい。

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/resources/views/admin/register.blade.php
> +                            <p class="mb-2 col-auto rounded bg-danger text-white">必須</p>
デザインより必須マークが大きくて、各項目のタイトルよりそっちばっか目が行っちゃいます。
更新画面はできてるのにもったいない！
![image](https://github.com/arimurashoi2000/newestKita/assets/108510903/5947cb58-d89b-43ec-a154-6894f7fe891f)

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/resources/views/layouts/app.blade.php
> +        @include('common.header')
membersとadmin_users両方ログインすると、ヘッダーが2つ表示されますよ！

■ユーザー機能
![image](https://github.com/arimurashoi2000/newestKita/assets/108510903/a914196f-95f9-45ec-8dfd-92d4d1c735b0)

■管理機能
![image](https://github.com/arimurashoi2000/newestKita/assets/108510903/cb2d33a3-561f-41ca-b7b8-6cd801a20a22)

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +    public function loggedOut(Request $request)
(同じメールアドレスの時だけかな？)
メンバーもしくは管理者をログアウトすると、もう片方もログアウトされてしまいます。
それぞれ分離されたログイン管理をするのが正しい姿ですよね。

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/resources/views/admin/tag_index.blade.php
> +                                    {{Form::text('name', null, ['class'=>'border border-secondary title col-md-12 col-12 mt-2 rounded text-center ms-3'])}}
text-center気持ち悪いかな。
あと検索が部分一致の方が優しいですよね。

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/Admin/AdminUserController.php
> +    {
今ログインしているユーザーを削除したらどうなりますか？

2023-08-17 01:27 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/Admin/AdminUserController.php
> +        }
結構上のロジックが肥大化しましたよね。
任せますが、AdminUser側にエスケープ処理を切り出してもいいかもですね。

2023-08-18 05:53 UTC, arimurashoi2000 commented on apps/kita/resources/views/common/admin_header.blade.php
> +<header>
承知しました。追加しておきました。

2023-08-18 05:55 UTC, arimurashoi2000 commented on apps/kita/resources/views/admin/index.blade.php
> +                                            <td>{{$adminUser->last_name}}{{$adminUser->first_name}}</td>
見落としていました。すみません。
全角スペースを追加しました。

2023-08-18 05:55 UTC, arimurashoi2000 commented on apps/kita/resources/views/admin/register.blade.php
> +                            <p class="mb-2 col-auto rounded bg-danger text-white">必須</p>
修正を忘れていました。
修正したので、お手隙の際に確認をよろしくお願いいたします。

2023-08-18 06:00 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/Admin/AdminUserController.php
> +    {
削除するとログイン画面に遷移します。

2023-08-18 06:50 UTC, arimurashoi2000 commented on apps/kita/resources/views/admin/index.blade.php
> +                                <div class="border rounded p-3 text-center custom-bg-lightgray">
修正しました。

2023-08-18 07:04 UTC, arimurashoi2000 commented on apps/kita/resources/views/common/pagination.blade.php
> +    @for ($page = $startPage; $page <= $endPage; $page++)
このページにコメントを入れておきました。

2023-08-21 00:01 UTC, arimurashoi2000 commented on apps/kita/routes/web.php
>  Route::resource('articles', ArticlesController::class)->only(['index', 'create', 'store', 'edit', 'update', 'show']);
最新のdevelopmentsからpullしてきました。
お手隙の際に確認をよろしくお願いいたします。

2023-08-21 00:02 UTC, arimurashoi2000 commented on apps/kita/routes/web.php
>  use App\Http\Controllers\Auth\LoginController;
ログアウト後にログイン画面にいくように修正しました。

2023-08-21 00:04 UTC, arimurashoi2000 commented on apps/kita/routes/web.php
> +Route::resource('/admin/article_tags', ArticlesTagController::class)->except(['show']);
admin系に対するグルーピングの適用と２１から２４行目を削除しました。

2023-08-21 00:05 UTC, arimurashoi2000 commented on apps/kita/resources/views/admin/index.blade.php
> +                        </div>
検索後に条件が残るように修正しました。お手隙の際に確認をよろしくお願いいたします。

2023-08-21 00:06 UTC, arimurashoi2000 commented on apps/kita/resources/views/layouts/app.blade.php
> +        @include('common.header')
app.blade.phpの条件を書き換えました。

2023-08-21 05:08 UTC, hikaru-yoshimura commented on apps/kita/resources/views/layouts/app.blade.php
> +        @include('common.header')
@arimurashoi2000 以下のif/elseifの配下の条件式は全く一致してます。
また、メンバーと管理者のon/offの組み合わせ的にも以下４つしかなく、それ意外の組み合わせないですよね。
ということは、この条件分岐ってそもそもここで必要でしょうか？
（現在ログインしているかどうかの認可は別途controller側で確認してて、勝手にリダイレクトしてくれるから不要と思うのです）

```
@if(Auth::guard('members')->check() && Auth::guard('admin_users')->check())
@elseif(!Auth::guard('members')->check() && !Auth::guard('admin_users')->check())
@elseif(Auth::guard('members')->check() && !Auth::guard('admin_users')->check())
@elseif(!Auth::guard('members')->check() && Auth::guard('admin_users')->check())
```

なお、今の12行〜44行の書き方的に、12通りの条件が発生している訳です。
これをテストするってのはかなりつらいですし、バグの温床です。
コーディングした時点で、このロジックは危ないなって気づいて、
シンプルにしようと思えるようになるといいですね。

もっとシンプルに考えると、以下ですよね。
メンバー：common.headerヘッダーが必要なのは、ログインと会員登録以外の画面
管理者：common.admin_headerヘッダーが必要なのは、ログイン以外の画面
となると、上記4つのif/elseifの配下の条件式になりますね(elseは書かなくていいですが)

2023-08-21 09:17 UTC, miokanedaC approved these changes
@arimurashoi2000 CC: @hikaru-yoshimura
コメントしました。特にクリティカルなものはなさそうなので、時間があれば直してください。

ただ、検索のところの%が二重に書かれているのは気になりますね。。

2023-08-21 09:17 UTC, miokanedaC commented on apps/kita/resources/views/layouts/app.blade.php
> +        @include('common.header')
↑ 私も吉村さんと可読性に関して問題が発生しているという点で同意です。
チーム開発において瞬時に可読できないようなプログラムは問題が発生しやすいし、問題発生からの解決をするのに時間がかかってしまいます。
そのためなるべくシンプルに書く書き方 + 汎用性のある書き方が望ましいです。

ifが多くなるであったり、階層が多くなる場合は毎回読みやすいように、改修コストが少ないようにできないかを考える癖をつけることが大事かと思います。

この場合、ifが多くなりすぎているので私だったら以下2点の修正をするかと思います。
**① layoutのファイルを切り分ける**
私だったら、以下3つに分けて、それぞれのbladeでlayoutをextendしている箇所ををかえるかな。
- layouts/app.php
- layouts/admin.php
- layouts/auth.php

**② 分岐の書き方を変える**
こちらに関しては多分吉村さんの考え方を取り入れて自分で考えたほうがいいかな。

2023-08-21 09:17 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +    public function loggedOut(Request $request)
こちらのアクセス修飾子が間違ってます。traitはprotectedなので、合わせたほうがいいかな。
まぁそもそもlogoutをoverrideしているところで関数名すら合わせなくてもいいんだけど、それだったら、このclass内でしか使われてないので、privateがいいと思います。
privateにするなら関数名を変えたほうがいいんだけど、そこまでやらないと行けないわけじゃないので、protectedを推奨します。

2023-08-21 09:17 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Auth/LoginController.php
> +        \Auth::guard('members')->logout();
```suggestion
        $this->guard()->logout();
```

こっちのほうが重複なくていいかなって思います。

2023-08-21 09:17 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Auth/LoginController.php
> +     * ログアウト機能
表現として、別にログアウトはしてないので、**ログアウト後の処理** かな

2023-08-21 09:17 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +    }
invalidateがsessionのstoreを全部消しちゃっている処理だったんですね。
そもそも今の実装だったら、logoutしてリダイレクトだけさせるんでいいようなきがするんでシンプルになるきがします。
regenerateTokenはloginのときにも走るので特に気にする必要内のかなって思ってたり。(あってもいいと思いますが)

```suggestion
    public function logout(Request $request)
    {
        $this->guard()->logout();
        
        return redirect()->route('showLoginForm');
    }
```

2023-08-21 09:17 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Auth/LoginController.php
> +        \Auth::guard('members')->logout();
AdminのLoginに書いたけどシンプルにできるかと思います。

2023-08-21 09:17 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/AdminUserController.php
> +            $admin_users->where('last_name', 'like', "%$escapedLastName%");
ここは書き方が変わっただけですかね？

2023-08-21 09:17 UTC, miokanedaC commented on apps/kita/app/Http/Middleware/Authenticate.php
> +            if (\Auth::guard('members')->guest() && !$request->is('admin/*')) {
おおもとを見てみると、unauthenticatedの場合呼び出される関数なので、こちらはguestかどうかの判定いらないような気がしますがどうですかね？？

2023-08-21 23:12 UTC, arimurashoi2000 commented on apps/kita/app/Http/Middleware/Authenticate.php
> +            if (\Auth::guard('members')->guest() && !$request->is('admin/*')) {
確かに指摘して頂いたとおり必要なかったので削除しました。

2023-08-21 23:24 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +    }
指摘して頂いた通りに修正しました。
membersとadmin_usersのどちらでもログインしている時にはどっちのguardをログアウトするか指定しないといけないと思っていたのですが、$this->guard()->logout();だけできちんと動いていて驚きました。
なぜguardに指定をしなくても片方だけログアウトされるのかピンときていないのでお手隙の際に教えていただけると嬉しいです。

2023-08-22 03:38 UTC, miokanedaC requested changes
@arimurashoi2000 
ちょっとlayoutのところ考え方のアドバイス書きました。
あとタグの検索ができてなかった気がします。確認お願いします。

2023-08-22 03:38 UTC, miokanedaC commented on apps/kita/app/Http/Middleware/Authenticate.php
> +            if ($request->is('admin/*')) {
elseで良さそうです。

2023-08-22 03:38 UTC, miokanedaC commented on apps/kita/resources/views/layouts/app.blade.php
>          @include('common.admin_header')
最後のelseの箇所がよく分からなかったかな。そもそもログインしているかどうかでページを見せるのはmiddlewareで管理しているのでここの分岐にはいらないような気がします。

コメントを書きながら書いたらいいと思うよ。そこから、シンプルにできるかどうか考えてやるのがいいかもね。
大きく分けて管理画面とユーザー画面があり、その中でも認証が通っているかいないかでわけられるので分けて書いてから整理していくといいかもしれないですね。MECEの考え方とかでやったらスッキリするかも。

```php
{{-- 管理画面 --}}
@if (request()->is(['admin/*']))
    {{-- 管理者ログイン中：ログイン画面以外のページが表示される仕組み --}}
    @if (\Auth::guard('admin_users')->check())
        @if (!request()->is(['admin/login']))
            @include('common.admin_header')
        @endif
    {{-- 管理者ログイン中以外：ログイン画面しか表示されない --}}
    @else
        @if (!request()->is(['admin/login']))
            @include('common.admin_header')
        @endif
    @endif
{{-- その他 (ユーザー画面) --}}
@else
    {{-- 会員ログイン中：すべてのページが表示される --}}
    @if (\Auth::guard('members')->check())
        @if (!request()->is(['login', 'member_registration'))
            @include('common.header')
        @endif
    {{-- 会員ログイン中以外：すべてのページが表示される --}}
    @else
        @if (!request()->is(['login', 'member_registration'))
            @include('common.header')
        @endif
    @endif
@endif
```
ユーザー画面：ログインしているかに関わらず全てのログイン・登録画面以外はcommonヘッダーを表示する必要がある
管理画面：ログインしているかで表示できるページが変わってくる。ログインしている場合はadminヘッダー それ以外はなし。
==> ログイン状況より変化というよりもページに依存している考え方がシンプル。
↓ 

```php
{{-- 管理画面 --}}
@if (request()->is(['admin/*']))
    {{-- ログイン以外は管理画面のヘッダーを見せる --}}
    @if (!request()->is(['admin/login']))
        @include('common.admin_header')
    @endif
{{-- その他 (ユーザー画面) --}}
@else
    {{-- ログイン / 登録画面以外はヘッダーを見せる --}}
    @if (!request()->is(['login', 'member_registration'))
        @include('common.header')
    @endif
@endif
```
↓
```php
{{-- 管理画面 --}}
@if (request()->is(['admin/*']))
    {{-- ログイン中に関わらず、ログイン以外は管理画面のヘッダーを見せる --}}
    @if (!request()->is(['admin/login']))
        @include('common.admin_header')
    @endif
{{-- その他 (ユーザー画面)　かつログイン中に関わらずログイン / 登録画面以外はヘッダーを見せる  --}}
@elseif (!request()->is(['login', 'member_registration'))
    @include('common.header')
@endif
```

2023-08-22 03:47 UTC, hikaru-yoshimura commented on apps/kita/resources/views/layouts/app.blade.php
> +        @include('common.header')
@arimurashoi2000 まだifが4つあって、わかりにくいので、アルゴリズム体操♪
```
01 @if (\Auth::guard('members')->check() && !request()->is(['login', 'member_registration', 'admin/*']))
02     @include('common.header')
03 @elseif (\Auth::guard('admin_users')->check() && !request()->is(['admin/login']) && request()->is(['admin/*']))
04     @include('common.admin_header')
05 @else
06     @if(!request()->is(['login', 'member_registration', 'admin/*']))
07         @include('common.header')
08     @elseif(!request()->is(['admin/*']) && !request()->is(['login', 'member_registration', 'admin/*']))
09         @include('common.admin_header')
10     @endif
11 @endif
```
現状のコードに番号振ったのでそれで読んで下さい。

- 06のBool条件は、01の右側のBool条件と一致してます。01と06の違いはメンバーログインしている人(01)としてない人(06)って事ですよね。でも実際、ログインと会員登録以外のメンバー機能ってメンバーログインによらず、メンバー用のヘッダー表示(02と07の処理)したいですよね。だからまとめられますよね。
- 08って&&前の条件は、後ろの条件に含まれてますよね。なので、以下のように書き換えれます。
`08    @elseif(!request()->is(['login', 'member_registration', 'admin/*']))`
その上で、08の条件ってなんでしょう？要は、「ログインと会員登録以外のメンバー機能」ですよね？なのに管理者ヘッダー表示したい(09)ってこと？ここを通るシナリオを思いつかないんです。単体テストしましたか？


さらに、認可はcontrollerでやっていることを鑑みると、以下2分岐まで絞れると思うんです。
テストしてないので、検討して欲しいです。どうでしょう？
```
01 @if (!request()->is(['login', 'member_registration', 'admin/*']))
02     @include('common.header')
03 @elseif (!request()->is(['admin/login']) && request()->is(['admin/*']))
04     @include('common.admin_header')
11 @endif
```

2023-08-22 06:53 UTC, arimurashoi2000 commented on apps/kita/resources/views/layouts/app.blade.php
>          @include('common.admin_header')
アドバイスありがとうございます。
確かにコメントを書きながらやると自分にも相手にもわかりにくいので活用して行きたいと思います。

2023-08-22 07:00 UTC, miokanedaC approved these changes
@arimurashoi2000 
良さそうです。
1点ユーザー画面の方の検索のページネーションが管理画面のレビュー前の状態と同じだったので、チケット作ってスケジュールとタイミング見つけて実施してください。

2023-08-22 07:04 UTC, miokanedaC commented on apps/kita/app/Http/Controllers/Admin/LoginController.php
> +    }
あ、ごめんなさいコメント見てなかった。
```php
$this->guard()->logout();
```
この$this->guard()を見てみるとAuth::guard('admin_users')になって指定しているのですでに書いてあるものは使いましょう精神です。

2023-08-23 06:49 UTC, merged