adminLTEアプトプットのレビュー依頼
arimurashoi2000/newestKita pull request #17
Opened 2023-08-25 06:00 UTC by arimurashoi2000

概要
管理者画面のヘッダー、サイドバー、フォームの入力項目にadminLTEを適用したので、お手隙の際に確認をよろしくお願いいたします。

受け入れ基準
・サイドバーは、管理者、会員、タグのそれぞれの管理画面へ飛べるようにアイコンとセットでaタグ、ログアウトボタンを記載する。
・全画面時にサイドバーを開くとその分wrapper部分が横にずれるようになっている。
・フォームの入力項目にadminLTEを使用している

関連チケット
url: https://fullspeed.atlassian.net/browse/WVQS-56

動画、画像

https://github.com/arimurashoi2000/newestKita/assets/126123174/380e91ac-d359-4583-b851-3348356bec67

https://github.com/arimurashoi2000/newestKita/assets/126123174/dd8e04f1-54fc-4218-9d9a-6f3708139f77

<img width="1728" alt="スクリーンショット 2023-08-25 14 51 36" src="https://github.com/arimurashoi2000/newestKita/assets/126123174/bb0cd246-6693-4e14-a40c-eefc13497df1">
<img width="1728" alt="スクリーンショット 2023-08-25 14 51 31" src="https://github.com/arimurashoi2000/newestKita/assets/126123174/177c2b7d-1211-4b3d-9ab5-bdb1573ce85b">

2023-08-25 09:56 UTC, hikaru-yoshimura requested changes
@arimurashoi2000 レビューしました！確認お願いします！

2023-08-25 09:56 UTC, hikaru-yoshimura commented on apps/kita/.gitignore
> +/public/js/
/public/fonts/配下も対象外にして、vendorのfontawesomeのフォントとかはコミットから除きましょう。

2023-08-25 09:56 UTC, hikaru-yoshimura commented on apps/kita/routes/web.php
この新しいルートと以下bladeは消し忘れですかね？
apps/kita/resources/views/adminLTE.blade.php
管理者ログインしてないのに見れたらいかんね。

あと、そのお陰で気づけたんですけど、
ログインしてない状態でURLを変更すると
- 管理者管理はログイン画面へ遷移してOK
- タグ管理(/admin/article_tags)と会員管理(/admin/users)はログインしてないのに見れちゃうのでダメですね。

2023-08-29 00:15 UTC, arimurashoi2000 commented on apps/kita/.gitignore
> +/public/js/
承知しました。gitignoreに追記してコミットから取り除くように修正したので、お手隙の際に確認をよろしくお願いいたします。

2023-08-29 00:17 UTC, arimurashoi2000 commented on apps/kita/routes/web.php
申し訳ございません。消し忘れていたので削除しました！
タグ管理、会員管理がログインしていなくても遷移できてしまう件も修正しました。

2023-08-29 00:38 UTC, merged