複数の記事削除機能のレビュー依頼
arimurashoi2000/newestKita pull request #18
Opened 2023-09-01 09:01 UTC by arimurashoi2000

概要
ajaxを使って複数の記事削除機能を作成しました。
自分の書いた記事を削除するにあたってマイページを作成し、マイページ上に自分が書いた記事のみ表示されるようになっています。

受け入れ基準
・自分の書いた記事の一覧が見れること
・記事を削除する機能が実装されていること
・記事を削除するボタンが実装されていること
・ボタンを押した時、記事が削除されていること

投稿者しか記事は削除できないことになっていること
関連チケット
url: https://fullspeed.atlassian.net/browse/WVQS-62

機能動画、画像

https://github.com/arimurashoi2000/newestKita/assets/126123174/22f0f2f4-2189-4401-9984-d1d9708a9004

<img width="1728" alt="スクリーンショット 2023-09-01 15 32 03" src="https://github.com/arimurashoi2000/newestKita/assets/126123174/950710f6-2456-4796-b6ac-62d2cbf77140">
<img width="1728" alt="スクリーンショット 2023-09-01 15 31 50" src="https://github.com/arimurashoi2000/newestKita/assets/126123174/ddab954c-24a2-4af1-aa14-f5828b547b08">

2023-09-04 04:51 UTC, hikaru-yoshimura requested changes
@arimurashoi2000 確認しました。

仕様が不明瞭なので、個々の理解によって実装がぶれちゃいますね。
次年度に向け改善します。

2023-09-04 04:51 UTC, hikaru-yoshimura commented on apps/kita/public/try/try.js
ゴミですかね？

2023-09-04 04:51 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ProfileController.php
元々、仕様が不明瞭ですので、直さなくていいです。
ただ、僕なら、こう思考するという事を記載しますね。
ーーーーーーーーーーーーーーーーーーーーーーーーーー
「Profile上で記事一覧を表示する案」について
・まずProfile上で記事一覧を用意するのはよくあるし、その上で削除するのは案としてはOK。
　ただ、記事一覧があるのだから、そちらで削除する事を検討するのが最初の案では？
　そもそも、記事の削除ロジックが、何故かProfileのコントローラーに出てくるのは気持ち悪い。
　→　迷ったら、上位者に聞く。
・通常の記事一覧と全く同じ構造となる為、片方を触ると、また片方を治す必要が出てくる。
　→　bladeは共通化したい
　(削除ボタン表示には、以下が差分くらいなので、blade分ける必要性ない。
　「ログインしてたら削除ボタン表示」
　「ユーザID＝投稿者IDが同じならチェックボックス表示。」)
・複数リソースを削除するロジックは、RESTfulの原則から逸脱している。
　記事のDestroyメソッドは、画面からAPIからも同じように１記事を削除するようにしておき、
　JavaScript側でループで何度もコールするようなロジックでも実装出来る。
　但し、今回のように一括削除のエンドポイントを実装するものありだとは思う。

　FEとBEが別れているプロジェクトの場合、前者はFEのみ改修修正。後者はFE/BE共に改修必要。
　但し、今回は自分で両方やるので、どちらでも可。

　→　正解はない。よって、修正は不要。実際のプロジェクトだと相談して欲しい。

　ちなみに、ChatGPTはどっちでもいいよって言ってる。
<img width="831" alt="image" src="https://github.com/arimurashoi2000/newestKita/assets/108510903/63c6dae9-88b8-43ff-ba1f-b20c15849dd0">

2023-09-04 04:51 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ProfileController.php
> +        $myArticle = Article::with('member')->orderBy('created_at', 'desc')->where('member_id', $member->id)->paginate(CommonConst::PAGINATION_ARTICLE);
$memberと$myArticleって使ってます？消し忘れ？

2023-09-04 04:51 UTC, hikaru-yoshimura commented on apps/kita/resources/views/admin/index.blade.php
> +</script>
このScriptって使われてます？

2023-09-04 04:51 UTC, hikaru-yoshimura commented on apps/kita/public/mix-manifest.json
> +    "/js/pagination.js": "/js/pagination.js",
mixに入れちゃうと、app.jsに組み込まれて、全画面に反映されるんですけど、
全画面でこのjs使います？

以下も同様です。
apps/kita/webpack.mix.js　
apps/kita/resources/views/layouts/app.blade.php

画面固有のjsは、その画面だけに取り込むようにしましょう。
https://nebikatsu.com/7231.html/

2023-09-04 04:51 UTC, hikaru-yoshimura commented on apps/kita/resources/js/articles_delete.js
> +                location.reload();
せっかくAJAX通信使って削除したのに、また他の部品も含め再読み込みするんじゃあまり意味ないですよね。

削除したIDを持っているんだから、blade側のdivに「row_数字（ID）」的なid振って
jqueryで「$( `#row_${ id }` ).remove();」って削除した方がスマートですよね。

2023-09-04 04:51 UTC, hikaru-yoshimura commented on apps/kita/resources/js/pagination.js
この壮大なJSは今も使われてますか？ページネーション考慮の残骸かな？

2023-09-05 02:14 UTC, arimurashoi2000 commented on apps/kita/resources/js/pagination.js
必要がない箇所があったのでそこは削除しました。
主にチェックボックスの状態をページネーションでページを移動した時にも保持しておくための処理を書いています。
名前もややこしいのでcheckbox.jsに変更しました。

2023-09-05 02:51 UTC, hikaru-yoshimura commented on apps/kita/resources/js/pagination.js
@arimurashoi2000 checkbox.jsもちょっと考えものかな？
例えば、チェックボックスがタグ管理にもあったら、どうします？
何のチェックボックスなのか明記したほうがいいかと思います。

2023-09-05 03:28 UTC, arimurashoi2000 commented on apps/kita/public/mix-manifest.json
> +    "/js/pagination.js": "/js/pagination.js",
先日はwebpackについて教えてくださってありがとうございました。
修正したのでお手隙の際に確認をよろしくお願いいたします。

2023-09-05 03:35 UTC, arimurashoi2000 commented on apps/kita/resources/js/pagination.js
承知しました。
ファイル名をarticles_checkbox.jsに変更して何のチェックボックスなのかわかるように修正しました。

2023-09-05 03:56 UTC, hikaru-yoshimura commented on apps/kita/public/mix-manifest.json
> +    "/js/pagination.js": "/js/pagination.js",
@arimurashoi2000 ちょいとフォルダの使い分けについて、改善してもらおうと思います。

[.gitignore](https://github.com/arimurashoi2000/newestKita/pull/18/files#diff-35201e0dd65b73ab4b068b79983cb4cfb135fa517c9a22ab6a5c16ce2c7761dcR20)で/public/js/を/public/js/app.jsに変えてますけど、なぜ元々/public/js/はコミット対象外なのか考えてみると、
[こちらの記事](https://stackoverflow.com/questions/32688672/best-practice-laravel-gitignore)に以下記載があります。
> Any generated content should not, if possible, be included in a git repo (and pushed)　
要は、webpackとかで生成されるものはコミット対象外にしようってことです。
なので、/public/js/はコミット対象外のままが良いと思います。

プロジェクトで作成した個別のJSは/public/assets/jsのフォルダ作って置きましょう。
実際のプロジェクトはこんな感じで管理してます。
<img width="233" alt="image" src="https://github.com/arimurashoi2000/newestKita/assets/108510903/e94baa09-ed60-4ed4-8753-b40d78a3992f">

2023-09-05 04:06 UTC, hikaru-yoshimura commented on apps/kita/resources/js/pagination.js
@arimurashoi2000 チェックボックスをつけて、別のページにいき、戻ってきたら、チェックボックスが元の画面で見れるような挙動ですかね？そのような動きは実装できてない気がします。
もし、特に削除に関係ない処理なのであれば、削除で良いかなと思います。
動く＆残すのであれば、どういう挙動か教えてください。

2023-09-05 06:02 UTC, arimurashoi2000 commented on apps/kita/public/mix-manifest.json
> +    "/js/pagination.js": "/js/pagination.js",
わざわざignoreしたのに違和感あるなあと感じていたのですが、別フォルダを作成すればよかったのですね。実際のプロジェクトでどのようにしているか知ることができてとても勉強になりました！
教えてくださってありがとうございます。

2023-09-05 06:06 UTC, arimurashoi2000 commented on apps/kita/resources/js/pagination.js
チェックボックスをつけた後に、他のページへ行き来しても、選択されたチェックボックスはそのままというような挙動です。
ただ、一通り動作確認した後にファイル名を変更してしまってビュー側で読み込むファイル名を変更し忘れていたため動作していない状態でした。
申し訳ございません。再度確認をよろしくお願いいたします。

2023-09-05 06:18 UTC, hikaru-yoshimura commented
LGTM!!!

2023-09-05 06:19 UTC, merged