会員登録、ログイン、ログアウト機能
arimurashoi2000/newestKita pull request #3
Opened 2023-07-04 08:21 UTC by arimurashoi2000

**概要**
会員登録機能、ログイン、ログアウト機能が完了したので、お手隙の際に確認をよろしくお願いいたします。

**受け入れ条件**
会員登録機能

・登録後は自動でログインも済ませる。
・登録画面は以下の項目が必須（ユーザの名前、メールアドレスの入力欄、パスワードの入力欄、パスワードの確認欄、登録ボタン）
・membersテーブルに情報が保存されること
・ユーザ名、メールアドレス、パスワードのバリデーションチェック
すでに登録されているものは登録できない（メールアドレス）
・その他のバリデーション
パスワード、パスワード確認欄は８文字以下
名前、パスワードは必須

ログイン、ログアウトの受け入れ基準
・ログイン画面にはメールアドレスと名前を入力する欄とログインボタンがある。
・ログアウトした後にログイン画面に戻るように設定。

関連するチケット
feature/WVQS-28_register
url: https://fullspeed.atlassian.net/jira/software/projects/WVQS/boards/222/backlog?epics=visible&selectedIssue=WVQS-28

feature/WVQS-29_loginlogout
url: https://fullspeed.atlassian.net/jira/software/projects/WVQS/boards/222/backlog?epics=visible&selectedIssue=WVQS-29

具体的な変更点
会員登録
・デフォルト会員機能をmembersテーブルを使って実装するためにconfig/authの変更
・memberモデル、マイグレーションファイルを作成
・membersテーブルに情報を保存するためにauth/registerControllerのメソッドを修正。

ログインログアウト
・auth/LoginControllerにAuthenticatesUsersからlogout機能をオーバーライドし、ログアウト後に/loginページに遷移するようにしたこと
・ルーティングにログインとログアウトのルーティングを記載。

機能動画
会員登録
https://github.com/arimurashoi2000/newestKita/assets/126123174/ea546fc0-c432-4f24-8c5b-a8c64ceafa92

ログインログアウト

2023-07-05 05:29 UTC, hikaru-yoshimura requested changes
@arimurashoi2000 まずは初プルリクお疲れ様です！
今が一番覚える事があり、沢山レビューコメントをもらう時でもあります。
全てが有村君の糧になると思って、食らいついて下さい！

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/app/Models/Member.php
> +// use Illuminate\Contracts\Auth\MustVerifyEmail;
不要なら消しましょう。他の人が見ると、なんでコメントアウトしたのか気になります。

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/app/Models/Member.php
> +use Laravel\Sanctum\HasApiTokens;
API使いますか？

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/app/Models/Member.php
> +        'remember_token',
remember_tokenはいりますか？これは何の為か理解していますか？
[DB定義](https://docs.google.com/spreadsheets/d/1rOaDBnJoagWrmqYwFD0Ak6C720BSv3y27h3AbfAj3bQ/edit#gid=1829368155)的には、不要ですが、改善の為ならOKです。

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/app/Models/Member.php
> +        'email_verified_at' => 'datetime',
メール認証はしますか？テーブル定義にはないですよね。不要なら消しましょう。

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/app/Models/Member.php
> +use Illuminate\Notifications\Notifiable;
メール認証はしますか？

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/config/auth.php
マルチログイン機能は未着のハズですので、admin_usersについてはレビュー対象から無視します。
ちなみに、未開発・未検証の機能を実装する場合は、PR概要かコード内に一筆コメント加えとくと、他メンバーに優しいです。

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/HomeController.php
後ほど消されるであろうControllerなのでレビュー対象から無視します。

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/vite.config.js
Laravel8までは、Laravel MixというCSSとJavaScriptのバンドルする為の、webpack.mix.jsというものを使っていました。
Laravel9からは、[Viteに置き換わったらしいですね](https://readouble.com/laravel/9.x/ja/vite.html)。

viteをコミットしているので、Laravel Mixは不要と判断しましたか？
であれば、webpack.mix.jsの削除について検討してみて下さい。
また、Laravel MixなりViteは何の目的の為にあるでしょうか？
今チケットでは使わないかもですが、CSSの拡張やAJAXなど使うチケットで深掘りするはずです。

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/resources/views/auth/register.blade.php
当Kita開発は実際のプロジェクトだと想定してみて下さい。
上流工程で先輩社員が頑張って、Kitaの[XD](https://xd.adobe.com/view/e8da9a44-98d7-46de-a97f-c1044c45497c-bd89/screen/f2ee1a49-19a8-46f1-b118-9a121fc945a5)を起こし、[DB設計](https://docs.google.com/spreadsheets/d/1rOaDBnJoagWrmqYwFD0Ak6C720BSv3y27h3AbfAj3bQ/edit#gid=1829368155)と[機能一覧＋URL設計](https://docs.google.com/spreadsheets/d/1OncMjJN0UWPgFDsKzSGt8ZNUkXhgTJcRzrgp-acSpvc/edit#gid=0)しました。
お客様と設計の合意をして、いざ作って下さいと有村君にお願いしました。

レビュー時、せっかく設計したのに、その通りになっていないと、どう思うでしょうか？
デザインは別チケットでやるなら、チケット概要に記載しました。
そうでないなら、他の画面も含め、デザインをやり直して下さい。終わってからデザインレビューします。

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/Auth/RegisterController.php
> +        return Validator::make($data, [
Validationしてエラーメッセージが表示されますが、英語のままです。
日本語適用してみましょう。

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/Auth/LoginController.php
> +use Illuminate\Http\JsonResponse;
Jsonログイン対応しますか？

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/Auth/ResetPasswordController.php
パスワードリセット機能は未着のハズですので、レビュー対象から無視します。

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/Auth/ForgotPasswordController.php
パスワードリセット機能は未着のハズですので、レビュー対象から無視します。

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/Auth/ConfirmPasswordController.php
パスワードリセット機能は未着のハズですので、レビュー対象から無視します。

2023-07-05 05:29 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/Auth/VerificationController.php
Email認証はしますか？

2023-07-05 06:22 UTC, arimurashoi2000 commented on apps/kita/app/Models/Member.php
> +        'remember_token',
全ての機能とデザインが終わった後に時間があったらremember_me機能使えた方が便利かなあと考え追加しておいたのですが、時間もなさそうなので、削除することにします。

2023-07-05 06:24 UTC, arimurashoi2000 commented on apps/kita/app/Models/Member.php
> +        'email_verified_at' => 'datetime',
メール認証は使う予定はないです。会員機能を実装する際にuserモデルをコピーしてmemberモデルを作成したのですが、必要な箇所のみ修正し、そのままの状態でした！削除しておきます。

2023-07-05 06:36 UTC, arimurashoi2000 commented on apps/kita/resources/views/auth/register.blade.php
承知しました！チケット概要の説明が不足していて申し訳ございません。
デザインは、ガントチャートにデザインの工程(8日分)があるので全てのユーザー側と管理者側の機能を作ってからデザインを進めていくつもりでした。
なので、今回は機能面のみのレビューをよろしくお願いいたします。

2023-07-05 07:15 UTC, arimurashoi2000 commented on apps/kita/app/Models/Member.php
> +use Illuminate\Notifications\Notifiable;
上記のテーブル定義と同様の理由で消していませんでした。
消しておきます。

2023-07-05 07:16 UTC, arimurashoi2000 commented on apps/kita/app/Models/Member.php
> +// use Illuminate\Contracts\Auth\MustVerifyEmail;
承知しました！不要だったので削除させていただきました。

2023-07-05 07:21 UTC, arimurashoi2000 commented on apps/kita/config/auth.php
申し訳ございませんでした。プルリクに説明を加えておきます！

2023-07-05 07:33 UTC, arimurashoi2000 commented on apps/kita/app/Models/Member.php
> +use Laravel\Sanctum\HasApiTokens;
userモデルをコーピーした際の記述をそのままにしていました。
SNSやメール認証などの外部アプリを今回は使用しないので、削除します。

2023-07-05 08:32 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/Auth/RegisterController.php
> +        return Validator::make($data, [
お疲れ様です。エラー文を日本語で表示できるように変更いたしました。

2023-07-06 04:48 UTC, hikaru-yoshimura commented on apps/kita/app/Models/Member.php
> +use Illuminate\Notifications\Notifiable;
@arimurashoi2000 未解決

2023-07-06 04:50 UTC, hikaru-yoshimura commented on apps/kita/vite.config.js
@arimurashoi2000 未解決

2023-07-06 04:58 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/Auth/RegisterController.php
> +        return Validator::make($data, [
@arimurashoi2000 pagination.phpとpasswords.phpもいれておくといいかもです。

2023-07-06 05:01 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/Auth/LoginController.php
> +use Illuminate\Http\JsonResponse;
@arimurashoi2000 ここを消したのであれば、
42行目以降logoutからも関連する記述を消しましょう。

2023-07-06 05:05 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/Auth/VerificationController.php
@arimurashoi2000 未着

2023-07-10 02:54 UTC, arimurashoi2000 commented on apps/kita/vite.config.js
ウェブサイトやアプリのフロントエンドを作るためのもので、viteはフロントエンドのアプリケーションを高速に開発するためのものでmixはjsやcssをまとめたり、圧縮したりできるものだと考えています。

viteの方をコミットしているのはこのregisterブランチでのみgit add .をしてしまったからでそこまで考えていませんでした。
package.jsonを見るとmixがされていてviteが使われていないので、vite.config.jsを削除しました。

2023-07-10 03:07 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/Auth/RegisterController.php
> +        return Validator::make($data, [
承知しました。/lang/jaにそれぞれ作成しました。

2023-07-11 04:53 UTC, hikaru-yoshimura commented on apps/kita/app/Models/Member.php
> +use Illuminate\Notifications\Notifiable;
@arimurashoi2000 Notifiableも不要ではないですか？

2023-07-11 10:07 UTC, hikaru-yoshimura requested changes
@arimurashoi2000 Blade周りを再度確認しました。
大分いい感じになってきましたね！

2023-07-11 10:07 UTC, hikaru-yoshimura commented on apps/kita/resources/views/auth/login.blade.php
> +                    {{ Form::open(['route'=>'login', 'files'=>true]) }}
Class "Form" not found
というエラーが発生します。
laravelcollective/html か spatie/laravel-html を入れましたよね？composer.jsonの更新はコミットされました？
PR時には、レビュー者の環境も意識してPushしましょう。

2023-07-11 10:07 UTC, hikaru-yoshimura commented on apps/kita/resources/views/auth/login.blade.php
> +                    <h1 class="border-bottom border-dark py-2"><strong>Kita</strong>ログイン</h1>
神は細部に宿りますので、僕は気になることを挙げます。
修正依頼ではないです。興味があれば、やってみて下さい。
(別チケットにして、全て終わった後の対応も可能)

ログイン／会員登録画面同様
・borderの色は、太さは、どうですか？
・ログイン「新規会員登録はこちら」の「こちら」に下線は必要ですか？
・ボタンの色はどうですか？
　(カラーピッカーでXDの色を確認し、
　resources/assets/sass/app.scssに定義して、
　webpack.mix.jsでコンパイルする)

2023-07-11 10:07 UTC, hikaru-yoshimura commented on apps/kita/resources/views/layouts/app.blade.php
> +        </nav>
nav必要ですか？
（ログイン後に必要であれば、resources/views/layouts/配下にnav.blade.phpみたいに作るのもいいですね。）

2023-07-11 10:07 UTC, hikaru-yoshimura commented on apps/kita/resources/views/auth/login.blade.php
> +
全体的に改行やインデントが気になります。他のblade及びPRも見直しをお願いします。
・コードを読みやすくなるように意味の区切りなどで改行を入れることはOKです。不用意に改行してないか確認しましょう。
・spanとかdivとか、開始と終了タグは並んでますか？兄弟タグと同じインデントになっていますか？構造的にインデントをすると読みやすくなります。
・少し改行やインデントのあるべき姿を検索し、修正してみて下さい。

2023-07-11 10:07 UTC, hikaru-yoshimura commented on apps/kita/resources/views/auth/login.blade.php
> +                                @endif
パスワードお忘れ機能はどうでしたっけ？

2023-07-11 10:07 UTC, hikaru-yoshimura commented on apps/kita/resources/views/auth/passwords/reset.blade.php
パスワード確認機能は未着のハズですので、レビュー対象から無視します。
・confirm.blade.phpとemail.blade.phpとverify.blade.phpは不要な気も。Controllerも不要な気も。
・reset.blade.phpは修正予定かと

2023-07-12 07:26 UTC, arimurashoi2000 commented on apps/kita/app/Models/Member.php
> +use Illuminate\Notifications\Notifiable;
不要だったので削除しました。教えてくださってありがとうございます。

2023-07-12 08:35 UTC, arimurashoi2000 commented on apps/kita/resources/views/auth/login.blade.php
> +                                @endif
リセット機能は実装するのですが、忘れた場合の機能は必要なかったので削除しました。

2023-07-12 08:37 UTC, arimurashoi2000 commented on apps/kita/resources/views/layouts/app.blade.php
> +        </nav>
使うことがないので削除しました。
ヘッダーはユーザーと管理者の方で必要なのですが、それぞれのディレクトリに作成することにします。

2023-07-12 08:41 UTC, arimurashoi2000 commented on apps/kita/resources/views/auth/login.blade.php
> +                    <h1 class="border-bottom border-dark py-2"><strong>Kita</strong>ログイン</h1>
レビュー修正も入れると予定日に間に合いそうにないので、ひとまずは全て終わった後で修正してみます。
修正点を教えてくださったのにも関わらず申し訳ございません。

2023-07-12 08:43 UTC, arimurashoi2000 commented on apps/kita/resources/views/auth/login.blade.php
> +                    {{ Form::open(['route'=>'login', 'files'=>true]) }}
composer.jsonに修正を入れてaddしようとしたのですが、git statusと打ってもcomposer.jsonが反映されない状態です。
gitignoreファイルに原因があるかもと考えたのですが、特に問題はなく、原因がわからないので少し時間がかかりそうです。
少々お待ちください。

2023-08-02 02:05 UTC, merged