記事一覧機能
arimurashoi2000/newestKita pull request #4
Opened 2023-07-05 02:40 UTC by arimurashoi2000

**概要**
記事一覧機能が完成したので、お手隙の際に確認をよろしくお願いいたします。

**受け入れ条件**
- 作成された記事の一覧が表示されていること
- 各記事のタイトルが表示されていること
- 各記事の作成者のuser名の表示
- 各記事の作成日時の表示
- 10ページずつのページネーション機能が実装されていること

関連チケット
feature/WVQS-32_articles_index
url: https://fullspeed.atlassian.net/browse/WVQS-32

具体的な変更点
・articleモデル、コントローラーを作成し必要なものを記入
・articles.blade.phpを作成し必要最低限のビュー画面を作成
・loginコントローラーの$redirectToの遷移先を一覧画面へ変更
・ダミーデータを作成するためにseederとfactoryファイルを作成し記入

2023-07-13 08:16 UTC, hikaru-yoshimura requested changes
@arimurashoi2000 確認しました。良くなってきましたね！
コメントさせてもらったので、対応お願いします！

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/database/seeders/DatabaseSeeder.php
> +        $this->call([MemberSeeder::class]);
php artisan db:seed;　すると  Target class [Database\Seeders\MemberSeeder] does not exist.　とエラー発生しますね。

seederが落ちると、記事が全くない状態なので、記事一覧はレビューできませんよね。
なので、Pushするときは、Seederでデータをきれいにして、動作確認を行った上でPushしましょう。

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/database/migrations/2023_07_01_094158_create_articles_table.php
> +            $table->unsignedBigInteger('id')->autoIncrement();
テーブル定義とあってますか？2147483647記事以上書くならBigIntでもいいですが...

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/database/migrations/2023_07_01_094158_create_articles_table.php
> +            $table->string('contents');
256文字しか記事が書けないですね...テーブル定義みてますか？

テーブル定義の1つ1つの値や命名などには、「思想」や「考え」があります。
それからずれた構築をするという場合には、きちんとした理由が必要となりますので、
必要な場合は設計者にコミュニケーションを取るか、レビュワーにPR概要などでその旨を伝えましょう。

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/database/migrations/2023_07_01_094158_create_articles_table.php
> +            $table->foreignId('member_id');
pull/3側でbig intで作られたのであれですが、BigIntいるかな？

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/database/seeders/ArticleSeeder.php
> +        Article::factory()->count(10)->create();
10記事ではページャーのテストができません。ページャーが出現する数よりも多く作成して下さい。

また、下の改行が多いのは意味ありますか？無駄な改行は消しましょう。

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/resources/css/app.css
app.cssに書いたのは適用されてますか？
webpack.mix.jsはどこからどこへCSSをコンパイルするんですっけ？

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/config/app.php
> +    'faker_locale' => 'ja_JP',
日本語に変えたいのはわかります。en_USの行を残す意味は？

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/database/factories/ArticleFactory.php
> +            'contents' => $this->faker->realText(50),
50文字は記事にしては短いですよね。
記事詳細のテストする時に、改行とかの確認することになるので、多めの文字数にする方がいいと思います。

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/database/factories/MemberFactory.php
> +            //
不要？

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +     */
追加でどんなことをやるのか、もう少し詳しく書いてあげるといいですね。
「記事一覧の表示を行う」的な処理概要。

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        $articles = Article::with('member')->orderBy('created_at', 'desc')->paginate(10);
withいいですね！
paginateの10はマジックナンバーなので、定数クラスなどにまとめてあげるといいです。

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        return view('articles.articles', compact('articles'));
articles.articlesはちょっとわかりにくいですよね。いい感じのファイル名を考えてみて下さい。

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/Auth/LoginController.php
> +    protected $redirectTo = '/articles';
この書き方だと、ルート側でURLを変更した時にバグになりますね。
articles.indexとかで記載した方がよいです。

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/header.blade.php
> +                                </svg>
SVGで表示するのもいいですが、font-awesomeでタグを埋め込むこともできます。
Kita作ったあとに勉強予定なので、今はいいですが、覚えておいて下さい。
(そんなに難しくないので、前倒ししてやってみるのもいいですよ！)

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/header.blade.php
artarticles専用のheaderになってしまっています。
もっと共通で使えるはずです。
head部分で共通でないのはtitleですね。
これを取り入れる為に@yieldと@sectionなどのディレクティブを使って変数化しましょう。
そうすれば、共通のファイルとできます。(例えば、app.blade.php使えますよね。)

そうすると、apps/kita/resources/views/articles/articles.blade.phpのheaderは消せますよね。

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/header.blade.php
> +            <nav class="navbar navbar-expand-lg navbar-light">
navも別bladeにしましょう。layouts内にnav.blade.phpとして置くといいですね。

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/header.blade.php
> +                    <a href="/articles" class="btn btn-success rounded-circle me-3" style="font-size: 2rem; padding: 0.5rem 2rem;">Kita</a>
/articlesだと、ルート側でURLを変更した時にバグになりますね。
href="{{route('articles.index')}}"とかで記載した方がよいです。

2023-07-13 08:16 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/header.blade.php
> +
改行２つは意味ありますか？

2023-07-24 04:44 UTC, arimurashoi2000 commented on apps/kita/database/migrations/2023_07_01_094158_create_articles_table.php
> +            $table->unsignedBigInteger('id')->autoIncrement();
間違えていたため、修正させていただきました。

2023-07-24 04:45 UTC, arimurashoi2000 commented on apps/kita/database/migrations/2023_07_01_094158_create_articles_table.php
> +            $table->string('contents');
承知しました。
mediumtextに修正しました。

2023-07-24 04:46 UTC, arimurashoi2000 commented on apps/kita/database/migrations/2023_07_01_094158_create_articles_table.php
> +            $table->foreignId('member_id');
members側とarticles側のどちらも修正をしておきました。

2023-07-24 04:47 UTC, arimurashoi2000 commented on apps/kita/database/seeders/ArticleSeeder.php
> +        Article::factory()->count(10)->create();
一度に４０記事を作成できるように修正しました。

2023-07-24 04:48 UTC, arimurashoi2000 commented on apps/kita/resources/css/app.css
bootstrapを適用する前にページネーションを作成したときにデザインが崩れてしまったので書いたのですが、今は必要ないので削除させていただきました。

2023-07-24 04:48 UTC, arimurashoi2000 commented on apps/kita/config/app.php
> +    'faker_locale' => 'ja_JP',
消し忘れていたため削除させていただきました。

2023-07-24 04:51 UTC, arimurashoi2000 commented on apps/kita/database/factories/ArticleFactory.php
> +            'contents' => $this->faker->realText(50),
確かに記事詳細で改行を確認するということを考慮していませんでした！５００文字の記事を作成できるように修正しました。

2023-07-24 04:52 UTC, arimurashoi2000 commented on apps/kita/database/factories/MemberFactory.php
> +            //
修正いたしました。

2023-07-24 04:52 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +     */
承知いたしました！今後も気をつけます。

2023-07-24 04:55 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        $articles = Article::with('member')->orderBy('created_at', 'desc')->paginate(10);
$article_numという変数にしてみました。
マジックナンバーが出ないように気をつけて作業を行います。

2023-07-24 04:56 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        return view('articles.articles', compact('articles'));
承知しました！index.blade.phpという名前に変更しました。

2023-07-24 05:14 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/Auth/LoginController.php
> +    protected $redirectTo = '/articles';
承知しました。変更しました。

2023-07-24 05:16 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/header.blade.php
title以外を共通化できるように書けたと思うのですが、あっている不安なのでお手隙の際に確認していただけると嬉しいです。

2023-07-24 07:00 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/header.blade.php
> +            <nav class="navbar navbar-expand-lg navbar-light">
ここのnavを別bladeにする理由が自分の勉強不足であまり理解できなかったので、教えていただけると嬉しいです。
管理者画面側でも使えるようにするためなのかなとも思ったのですが、管理者画面側のヘッダーとは内容やデザインがかけ離れているので共通のものとしても使えないですし、考えてみたのですが他の理由を思いつけないので教えていただけると嬉しいです。

2023-07-24 07:07 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/header.blade.php
> +                    <a href="/articles" class="btn btn-success rounded-circle me-3" style="font-size: 2rem; padding: 0.5rem 2rem;">Kita</a>
承知しました。indexに修正しておきました。

2023-07-24 07:08 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/header.blade.php
> +
意味がないので、削除させていただきました。

2023-07-26 09:38 UTC, hikaru-yoshimura commented on apps/kita/database/migrations/2023_07_01_094158_create_articles_table.php
> +            $table->foreignId('member_id');
articles側はまだBigintの気がします。

2023-07-26 09:51 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        $articles = Article::with('member')->orderBy('created_at', 'desc')->paginate(10);
今の実装だとマジックナンバーを変数に置き換えちゃっただけで、変数は変えられちゃいますよね？定数にしましょう。
また定数クラスを調べて実装して下さい。

2023-07-26 10:04 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/header.blade.php
ディレクトリ的にもまだarticles専用ですね。layouts/app.blade.phpにhead部分は移動して下さい。それをarticles.blade.phpをextendsしましょう。
またindex.blade.phpで<head>用意してますけど、header.blade.phpにも<head>があり、二重になっちゃってます。titleは上述の通り@yieldと@sectionを使って共通化して下さい。

2023-07-26 10:06 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/header.blade.php
> +            <nav class="navbar navbar-expand-lg navbar-light">
管理者画面は別のheaderを作ります。記事系のbladeは複数作りますよね？headerで共通化しておかないと、毎回同じコードを書くことになってしまいます。

2023-07-27 05:27 UTC, arimurashoi2000 commented on apps/kita/database/migrations/2023_07_01_094158_create_articles_table.php
> +            $table->foreignId('member_id');
すでに画像のようにプルリクを出す前にgithub上でも変更されているように見えるのですが、どうでしょうか。
<img width="1720" alt="スクリーンショット 2023-07-27 14 25 17" src="https://github.com/arimurashoi2000/newestKita/assets/126123174/1d0817e8-8d91-41d3-b927-00a090b97be9">
<img width="1725" alt="スクリーンショット 2023-07-27 14 24 55" src="https://github.com/arimurashoi2000/newestKita/assets/126123174/fb975c3d-3218-4a8d-b32c-552a77ae5fef">
<img width="1714" alt="スクリーンショット 2023-07-27 14 24 41" src="https://github.com/arimurashoi2000/newestKita/assets/126123174/78ad82aa-533e-453f-ba33-525988a0f637">

2023-07-27 06:06 UTC, hikaru-yoshimura commented on apps/kita/database/migrations/2023_07_01_094158_create_articles_table.php
> +            $table->foreignId('member_id');
Github上ではなく、実際にDBはどうなってますか？

2023-07-27 07:02 UTC, arimurashoi2000 commented on apps/kita/database/migrations/2023_07_01_094158_create_articles_table.php
> +            $table->foreignId('member_id');
articlesのidは適切だったのですが、member_idがまだunsigned bigintでした。
公式ドキュメントを読んだところforeignIdメソッドはunsigned bigintになる見たいなので方法を調べて修正します。

2023-08-01 05:56 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        $articles = Article::with('member')->orderBy('created_at', 'desc')->paginate(10);
app\Consts\CommonConst.phpというファイルを作成し、コントローラーで定数を使えるように書いてみました。
もし間違っていたら教えていただけたら嬉しいです。
よろしくお願いいたします。

2023-08-01 05:57 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/header.blade.php
デザインの書き方を修正したのでお手隙の際に確認していただけると嬉しいです。

2023-08-01 05:58 UTC, arimurashoi2000 commented on apps/kita/database/migrations/2023_07_01_094158_create_articles_table.php
> +            $table->foreignId('member_id');
refeerencesを使って修正しました。

2023-08-01 09:29 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        $articles = Article::with('member')->orderBy('created_at', 'desc')->paginate(10);
いいと思います！
あとは、使う側で以下のように変数に入れてますけど、
せっかく定数作ったのに、変数は編集できてしまいますよね。
そのまま使った方が素直だと思いました。

$paginationLimit = CommonConst::PAGINATION_ARTICLE;

2023-08-01 09:53 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/header.blade.php
blade関係はまとめてコメント記載します。

1. app.blade.php に以下あり、bodyの中にはheaderしかないのかなって思ってしまうので、
@yield('content')の方が正しいと思います。
```
<body>
    @yield('header')
</body>
```

2. nav.blade.php に以下あり、ナビゲーションは単純なので、依存関係記載しなくて、単純なHTMLにしてもいいと思います。
```
@extends('articles.header')
@section('nav')
〜
@endsection
```

3. 記事に共通でnavを作って上げる為に作ったのかと思いますが、header.blade.php は冗長なので、
app.blade.php側にヘッダーとかフッター入れるのでもいいかと。
管理画面系とユーザー画面系のヘッダー別々に用意してif文で分ければいいですね。

2023-08-03 05:33 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/header.blade.php
承知しました。header.blade.phpをcommonsに入れるか迷いましたが、デザインを見てみたらログイン、ログアウト機能でもヘッダーを使わなかったのでそのままarticlesに入れておきました。

2023-08-03 05:34 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        $articles = Article::with('member')->orderBy('created_at', 'desc')->paginate(10);
承知しました！確かに定数を作った意味がなくなってしまうので、そのまま使うようにしました。

2023-08-03 08:27 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/header.blade.php
@arimurashoi2000 プロフィール更新でも同じヘッダー使うはずですので、commonディレクトリに移して下さい。
https://xd.adobe.com/view/e8da9a44-98d7-46de-a97f-c1044c45497c-bd89/screen/261aef36-c05a-4a6c-bab7-2211af5f30e1

2023-08-03 08:31 UTC, hikaru-yoshimura requested changes

2023-08-03 08:31 UTC, hikaru-yoshimura commented on apps/kita/app/Models/Member.php
> +    public function isAdmin()
これは何に使ってますか？つかわれてないなら、コミット不要かと。

2023-08-03 08:31 UTC, hikaru-yoshimura commented on apps/kita/resources/views/layouts/app.blade.php
> +        @include('admin.header')
admin.headerはまだないので、通ると落ちますよね。
そういうのはまだコミットしない方が正しいです。共同開発の時に、何のコードだろうってなるので。
もし事前なら、前もって空のヘッダー作っておいて、実装予定ということを記載しましょう。

2023-08-03 22:39 UTC, arimurashoi2000 commented on apps/kita/app/Models/Member.php
> +    public function isAdmin()
すみません、消し忘れていました。
ミドルウェアがadmin側かどうかを判別するメソッドを作ろうとしたのですが、制作途中でauth()->guardを使えばいいと気がつき消し忘れたものなので削除しておきます。

2023-08-03 22:40 UTC, arimurashoi2000 commented on apps/kita/resources/views/layouts/app.blade.php
> +        @include('admin.header')
事前に書いておきたいのでからのヘッダーを作り実装予定だということを記載しました。

2023-08-04 06:22 UTC, arimurashoi2000 commented
マージするため。

2023-08-04 06:22 UTC, arimurashoi2000 commented
マージするため。

2023-08-04 07:09 UTC, merged