検索機能のレビュー依頼
arimurashoi2000/newestKita pull request #5
Opened 2023-07-06 03:39 UTC by arimurashoi2000

**概要**
記事一覧機能が完成したので、お手隙の際に確認をよろしくお願いいたします。
デザインは全機能終了後に反映するので、機能面のみ確認をよろしくお願いいたします。

**受け入れ条件**
作成された記事の一覧が表示されていること
各記事のタイトルが表示されていること
各記事の作成者のuser名の表示
各記事の作成日時の表示
10ページずつのページネーション機能が実装されていること
関連チケット
feature/WVQS-32_articles_index
url: https://fullspeed.atlassian.net/browse/WVQS-33

**具体的な変更点**
・articleコントローラーにsearchメソッド
・articles.blade.phpに検索フォームとエラー表示の記述を追加
・バリデーションを追加(＃や％を検索できないようにする)

2023-07-18 08:10 UTC, hikaru-yoshimura requested changes
@arimurashoi2000 取り急ぎルートとコントローラーだけ見ました。
bladeとseederは前のプルリクが反映されると思うので、それまで待ちます。

2023-07-18 08:10 UTC, hikaru-yoshimura commented on apps/kita/routes/web.php
> +Route::get('/articles/search', [ArticlesController::class, 'search'])->name('articles.search');
別のURLを切るのではなく、機能一覧に指定されたようにGetパラメーターで指定しましょう。
/articles?search=foobar

(機能一覧は仕様ですので、違うURLを利用するなら、仕様変更を上位者に相談しましょう。)

コントローラーのindex内にsearchファンクションを組み込む感じですね。

2023-07-18 08:10 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +            'keyword' => ['regex:/^[^%#]+$/'],
@%や#のバリデーションを掛けるのはどうですかね？(エラー文言も日本語のままだし)
ユーザーが「100%ジュース」って検索したいかもしれませんよね。
SQLのWHERE文にわたす時にaddcslashesとかでエスケープ処理してあげるといいです。

2023-07-24 08:07 UTC, arimurashoi2000 commented on apps/kita/routes/web.php
> +Route::get('/articles/search', [ArticlesController::class, 'search'])->name('articles.search');
承知しました！articles?search=を勘違いしていたのですが、articlesのままsearch(渡すname名)=キーワード名ということですね。修正したので、確認をよろしくお願いいたします。
コントローラーのindex内にsearchファンクションを組み込む感じというのが勉強不足であまり理解できなかったのですが、一応実装できたので間違っていたらまた教えていただけると嬉しいです。よろしくお願いいたします。

2023-07-24 08:08 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +            'keyword' => ['regex:/^[^%#]+$/'],
確かに%を文字列として使う場合を想定していませんでした！
教えていただいたaddcslashesを使用して修正をしたのでお手隙の際に確認をよろしくお願いいたします。

2023-08-07 01:28 UTC, hikaru-yoshimura requested changes
追加のコメントです。対応お願いします。

2023-08-07 01:28 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/header.blade.php
articles/header.blade.phpは不要になりましたよね？

2023-08-07 01:28 UTC, hikaru-yoshimura commented on apps/kita/resources/views/common/header.blade.php
> +            @csrf
getパラメーターにtokenがつくのが気持ち悪いので消して下さい。
https://teratail.com/questions/170697

2023-08-07 01:28 UTC, hikaru-yoshimura commented on apps/kita/resources/views/common/header.blade.php
> +                </form>
検索窓が２つ表示されているので統一しましょう。

2023-08-07 01:28 UTC, hikaru-yoshimura commented on apps/kita/database/seeders/ArticleSeeder.php
pull/5で以下やると、
```
php artisan migrate:fresh;
php artisan db:seed;
```

以下のエラーが出ます。確認お願いします。
```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`kita`.`articles`, CONSTRAINT `articles_member_id_foreign` FOREIGN KEY (`member_id`) REFERENCES `members` (`id`)) (SQL: insert into `articles` (`title`, `contents`, `created_at`, `updated_at`, `member_id`)
```

2023-08-07 03:33 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/header.blade.php
はい。デザインを反映したことで必要なくなったので削除させていただきました。

2023-08-07 03:34 UTC, arimurashoi2000 commented on apps/kita/resources/views/common/header.blade.php
> +            @csrf
承知しました。他のブランチでもget時にcsrfを使ってしまっていた箇所があるので、その都度修正していきます。

2023-08-07 03:36 UTC, arimurashoi2000 commented on apps/kita/resources/views/common/header.blade.php
> +                </form>
申し訳ございません。デザインが反映されてから消すのを忘れていました。以後気をつけます。

2023-08-08 06:12 UTC, merged