記事作成機能のレビュー依頼
arimurashoi2000/newestKita pull request #6
Opened 2023-07-25 04:02 UTC by arimurashoi2000

概要
記事一覧機能が完成したので、お手隙の際に確認をよろしくお願いいたします。

受け入れ条件

作成された記事の一覧が表示されていること
各記事のタイトルが表示されていること
各記事の作成者のuser名の表示
各記事の作成日時の表示
10ページずつのページネーション機能が実装されていること
記事を作成した順で表示(記事編集画面で修正済み、マージ後に戻ってくる)

関連チケット
feature/WVQS-32_articles_index
url: https://fullspeed.atlassian.net/browse/WVQS-30

具体的な変更点
・headerの記事作成ボタンから遷移できるようにする
・articles.create.phpを作成
・ルーティングに新規記事追加のためのルーティングを記載
・articlesコントローラーに記事遷移と記事追加の機能を記載

機能動画

https://github.com/arimurashoi2000/newestKita/assets/126123174/41e6c20e-6ff1-4a21-b85f-dcebdb417784

<img width="1728" alt="スクリーンショット 2023-07-25 12 45 56" src="https://github.com/arimurashoi2000/newestKita/assets/126123174/ef300dc3-b3d8-451d-a7f3-36437e167fa1">

2023-07-27 01:09 UTC, hikaru-yoshimura requested changes
@arimurashoi2000 取り急ぎ、blade以外をさらっと見ました。

2023-07-27 01:09 UTC, hikaru-yoshimura commented on apps/kita/routes/web.php
> +Route::post('/articles', [ArticlesController::class, 'store'])->name('store')->middleware('auth');
せっかくなので、[Resource](https://zenn.dev/naoki_oshiumi/articles/e34de678377869)を使ってみましょう。
なお、[機能一覧](https://docs.google.com/spreadsheets/d/1OncMjJN0UWPgFDsKzSGt8ZNUkXhgTJcRzrgp-acSpvc/edit#gid=0)のMethod/URLがなぜああやって定義されているのか同時に考えて見て下さい。

2023-07-27 01:09 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_create.blade.php
> +</head>
記事一覧のPR側で<head>はまだ修正されると思いますので、備忘録コメント。

2023-07-27 01:09 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_create.blade.php
> +                            </div>
タグ未実装ですよ！！

2023-07-27 01:09 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        return redirect()->route('index');
[仕様](https://xd.adobe.com/view/e8da9a44-98d7-46de-a97f-c1044c45497c-bd89/screen/88359b5e-e16d-4b77-a7f5-82a429f6eb28)をよく見ましょう。
<img width="261" alt="image" src="https://github.com/arimurashoi2000/newestKita/assets/108510903/2668bb69-4148-49ed-b8fc-2df8da0c2ff0">

2023-07-27 01:09 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        $article->member_id = auth()->id();
今は項目が３つなのでこうやって書けますけど、列が数10個あるテーブルだと漏れずミスなくに全て記載するのって大変ですよね。
なので、[この記事](https://qiita.com/henriquebremenkanp/items/cd13944b0281297217a9#%E8%81%B7%E4%BA%BA-1)みたいに、`$user->fill($request->all())->save();`　っていう具合にRequestのfill設定した項目を全て保存する事ができます。

member_idだけは[この記事](https://programing-school.work/laravel-add-parameta-request/)見たいに$request->merge機能を使うといいですね。

あと、$validatedって肥大化しがちなので、[この記事](https://cloudsmith.co.jp/blog/backend/laravel/2022/03/2052565.html)見たいにcontrollerから引きはがすこともできます。

2023-08-01 07:42 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        return redirect()->route('index');
承知しました。記事作成を記事編集機能よりも先に作ってしまったため、とりあえず現時点では記事作成画面へリダイレクトするように書き、変更するのを忘れないようにコントローラー上にコメントを残しておきました。

2023-08-01 07:44 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles_create.blade.php
> +                            </div>
はい。ただ、タグを実装することは必須なので、このように書いておけばタグを実装した後にこのビュー上のどこに書けばいいか分かりやすいと思い書いておきました。

2023-08-01 07:46 UTC, arimurashoi2000 commented on apps/kita/routes/web.php
> +Route::post('/articles', [ArticlesController::class, 'store'])->name('store')->middleware('auth');
承知しました！記事編集のurlなどでは自分たちが作ったurlとは異なりidが先に来て少し違和感を感じていたのですが、どうしてこのようなurlが指定されているの理解することができました。

2023-08-04 08:36 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_create.blade.php
> +                            </div>
そういうことではなくて、
機能一覧で記載のある管理者管理のタグ管理はあくまでタグを管理する機能を構築するんですよね。
なので、タグデータをシードしておけば、見る側はタグの実装できますよね。

2023-08-04 08:37 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        return redirect()->route('index');
あぁ、そういう事ですね、了解！

2023-08-04 09:31 UTC, hikaru-yoshimura requested changes
追加コメントします。pull/4の反映をお願いします。

2023-08-04 09:31 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles.blade.php
> +@include('articles.header')
多分まだpull/4のマージができてないですね。common.headerになってますし、上の方の<head>は不要ですね。

2023-08-04 09:31 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles.blade.php
> +</body>
`</body>`が2行上にもあって、そもそも`<body>`がない気がします。

2023-08-04 09:31 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_create.blade.php
> +</head>
直ってないですね。一覧で作ったcommon.headerとかを反映しましょう。

2023-08-04 09:31 UTC, hikaru-yoshimura commented on apps/kita/routes/web.php
> +    ]);
resourceの時namesいるかな？
view側で使いたかった感じですか？
Request::routeIs('articles.edit')とかで取れるし、不要な気も。

2023-08-07 05:06 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        return redirect()->route('index');
TODOを使ってみたらすごくみやすくなりました！
教えてくださってありがとうございます。

2023-08-07 06:50 UTC, arimurashoi2000 commented on apps/kita/routes/web.php
> +    ]);
route::resourceを使ったときに自動的にルート名も付与されることを知らなかったため、ビュー側やリダイレクト時に使うために設定していました。

2023-08-07 06:56 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles.blade.php
> +@include('articles.header')
はい。先週の金曜はpull4を5に反映するところで終わってしまったので、まだpullできていない状態でした。articles.blade.phpファイル自体pull4でindex.blade.phpに置き換わったので削除しました。

2023-08-07 06:58 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles_create.blade.php
> +                            </div>
承知しました。チーム開発時にタグ機能実装後に記事側でタグを追加、編集などの機能を追加していったのでタグ機能後に行うつもりでしたが、このブランチ内で今から行います。

2023-08-08 04:18 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +        $article->member_id = auth()->id();
fillを使って一括で挿入するようにしました。
他のブランチでも適用していきます。

2023-08-08 07:48 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_create.blade.php
> +</head>
@arimurashoi2000 良くなりました！

@section('title') と @section('content')の段落が揃ってないので、index.blade.phpとarticles_create.blade.phpで直しておいて下さい。
あとapp.blade.phpもbody配下が段落ないので読みづらいです。

2023-08-08 07:53 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_create.blade.php
> +                            </div>
@arimurashoi2000 シーダーで以下エラー発生します。確認お願いします。
レビュー依頼前に一回まっさらにしてテストする事をおすすめします。
```
php artisan migrate:fresh;
php artisan db:seed;

```

エラー内容
```
Database\Seeders\ArticleSeeder ........................................................................................................... RUNNING

   InvalidArgumentException

  You requested 3 items, but there are only 0 items available.

  at vendor/laravel/framework/src/Illuminate/Collections/Arr.php:632
    628▕
    629▕         $count = count($array);
    630▕
    631▕         if ($requested > $count) {
  ➜ 632▕             throw new InvalidArgumentException(
    633▕                 "You requested {$requested} items, but there are only {$count} items available."
    634▕             );
    635▕         }
    636▕

      +1 vendor frames
  2   database/seeders/ArticleSeeder.php:20
      Illuminate\Support\Collection::random()

      +1 vendor frames
  4   database/seeders/ArticleSeeder.php:21
      Illuminate\Support\Collection::each(Object(Closure))
```

2023-08-08 08:23 UTC, hikaru-yoshimura commented
@arimurashoi2000 言い忘れました。
「記事を作成する」ボタンから作成するとURLの末尾に?が入ります。
また、タグだけ何故かパディングされてます。
![image](https://github.com/arimurashoi2000/newestKita/assets/108510903/a586b9cf-531f-4532-bfab-896c77f0805e)

2023-08-08 08:50 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles_create.blade.php
> +                            </div>
承知しました。レビュー依頼をする前にrefresh、db:seedをセットで行うよう心がけます。

2023-08-09 00:45 UTC, merged