記事編集機能のレビュー依頼
arimurashoi2000/newestKita pull request #7
Opened 2023-07-25 05:14 UTC by arimurashoi2000

概要
記事一編集機能が完成したので、お手隙の際に確認をよろしくお願いいたします。
記事編集ボタンは本来記事詳細に設置されますが、まだ記事詳細機能を作成していないので記事一覧に置いています。

受け入れ条件
記事作成画面ではタイトルと記事内容を入力することができること
仮の記事編集ボタンを押すと記事が作成されて記事一覧画面に遷移すること
記事作成画面は以下の項目を必須とする
タイトル入力欄
・記事内容入力欄
・保存するボタン

タイトルと本文のバリデーションチェック
・タイトルと本文は入力必須
・タイトルには文字数制限があること
・本文に文字制限がかかっていること
バリデーションにひっかかるとエラーを返し、画面に表示すること

関連チケット
url: https://fullspeed.atlassian.net/browse/WVQS-34

具体的な変更点
・articlesに仮の編集ボタンを置く
・編集用のビューファイルを作成
・コントローラーに遷移する
・ダミーデータを作成するためにseederとfactoryファイルを作成し記入

機能動画

https://github.com/arimurashoi2000/newestKita/assets/126123174/8e951fe3-0cc4-4091-93e7-c57af531fda5
<img width="1223" alt="スクリーンショット 2023-07-25 13 25 04" src="https://github.com/arimurashoi2000/newestKita/assets/126123174/2c5f5b69-7098-4d44-a5d4-499fbf3b5e0c">
<img width="1728" alt="スクリーンショット 2023-07-25 13 24 32" src="https://github.com/arimurashoi2000/newestKita/assets/126123174/849ad0a5-c5ca-4b2e-bf71-a0874586eb08">

2023-08-04 09:55 UTC, hikaru-yoshimura requested changes
全体的にPull/4&5&6のコメント反映をお願いします。

2023-08-04 09:55 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +    public function edit($id) {
要件はないですけど、せっかく有村さんが頑張って書いた記事が違う人に編集されたら嫌ですよね？
「作成者と同じログインユーザ場合のみ更新、それ以外は記事詳細に飛ばす」的な処理入れるといいですね。

あと本日のLTで話したルートモデルバインディングしましょ。

2023-08-04 09:55 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_edit.blade.php
> +                        <!--タグ-->
作成同様、タグ編集機能を付けましょう。

2023-08-04 09:55 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +            'contents' => 'required|max:400',
storeと違うバリデーションでは、新規で登録できたのに編集できなくなりますよね。
Validatorとして切り出して、新規と編集で共通に使えるようにしましょう。

2023-08-04 09:55 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +    public function update(Request $request, $id) {
$idではなくルートモデルバインディングで。

2023-08-06 08:41 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +            'contents' => 'required|max:400',
承知しました。
validatorの切り出し方が合っているか不安なのでお手隙の際に確認をよろしくお願いいたします。

2023-08-06 09:15 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +    public function update(Request $request, $id) {
承知しました。ルートモデルバインディングを使って実装しました。

2023-08-08 21:05 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +    public function edit($id) {
承知しました。ログインユーザーのみ更新できるよう変更しました。
リダイレクト先は記事詳細機能時に記事詳細画面へ行けるよう修正します。

2023-08-09 02:41 UTC, hikaru-yoshimura requested changes
@arimurashoi2000 再度確認しました。追加修正お願いします。

2023-08-09 02:41 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_create.blade.php
> +    <title>記事一覧</title>
記事一覧？

2023-08-09 02:41 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_create.blade.php
> +                <!--TODO 記事編集機能完成後はこの記述を編集画面へ移動させる-->
TODOのまま

2023-08-09 02:41 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_edit.blade.php
> +                @endif
ここらのflashメッセージは共通化できるので、別bladeにするとスッキリしますね。
別の機能でも同じように書くと思いますので。

2023-08-09 02:41 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_edit.blade.php
任せますが、articles_createと共通化も可能ですね。

2023-08-09 02:41 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_edit.blade.php
> +                                            <option value="{{$tag->id}}">{{$tag->name}}</option>
新規ですでにタグが選択してあったら、編集画面ではそれらが選択されているべきですね。
例えば３つタグを新規画面で作成して、編集画面を開いてそのまま編集すると、画面上は何もタグを選択してないのに、３つ登録されたままになっています。見た目と実データが合うようにしましょう。

2023-08-09 02:45 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +            'contents' => 'required|max:400',
@arimurashoi2000 いい感じです。
タイトルか記事内容を空にして、更新すると、member idのエラーもでるので追加で直して下さい。
![image](https://github.com/arimurashoi2000/newestKita/assets/108510903/b12fe647-7911-4fbb-90c3-6b71a040b954)

2023-08-09 03:42 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +            'contents' => 'required|max:400',
承知しました。修正しました。

2023-08-09 03:42 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles_edit.blade.php
> +                                            <option value="{{$tag->id}}">{{$tag->name}}</option>
確かにそうですよね。修正しました。

2023-08-09 03:47 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles_create.blade.php
> +    <title>記事一覧</title>
修正しました。

2023-08-09 03:51 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles_edit.blade.php
> +                @endif
flashメッセージをcommonディレクトリにflash_message.blade.phpとしてかき、編集画面でincludeしました。確認をよろしくお願いいたします。

2023-08-09 03:54 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles_edit.blade.php
時間がすでに遅れてしまっているので、全ての修正が終わった後で取り組もうと思います。
編集画面は新規登録で登録した情報を表示しておかなければならないため、そこをどう分けて共通化できるのか現時点では思いつかないので考えておきます。

2023-08-09 05:29 UTC, merged