記事詳細機能のレビュー依頼
arimurashoi2000/newestKita pull request #8
Opened 2023-07-25 06:26 UTC by arimurashoi2000

概要
記事詳細表示機能が完成したので、お手隙の際に確認をよろしくお願いいたします。
 削除ボタンは実装後に行います。
編集ボタンを押した後編集ページに移動しますが、デザインは編集機能マージ後に反映されます。

受け入れ基準

画面には以下の項目が表示されていること
・タイトル
・コンテンツ
・作成者
・作成日
・タグ(タグ機能実装時)
・削除、編集ボタン

関連チケット
url: https://fullspeed.atlassian.net/browse/WVQS-35

具体的な変更点
・詳細ページの編集ボタンから飛べるようにする
・詳細ようのビュー画面を作成
・記事コントローラーに詳細画面に遷移するためのメソッドを追加

機能動画
https://github.com/arimurashoi2000/newestKita/assets/126123174/859e7bb5-9f97-4faa-9019-85f232175f98

2023-08-04 10:10 UTC, hikaru-yoshimura requested changes
全体的にPull/4&5&6&7のコメント反映をお願いします。

2023-08-04 10:10 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_show.blade.php
> +                        <!--削除、編集用のボタン-->
ログインユーザーの場合のみボタン表示って仕様では？

2023-08-04 10:10 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles.blade.php
articlesとindexの違いってなんですっけ？

2023-08-08 00:46 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles.blade.php
同じファイルだったのですが、viewで遷移するときにarticles.articlesとなってしまってわかりにくいというアドバイスを頂いたので、pull4でindex.blade.phpに変更させていただきました。

2023-08-09 07:02 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles_show.blade.php
> +                        <!--削除、編集用のボタン-->
すみません。要件を見逃していたので、修正しました。

2023-08-09 08:54 UTC, hikaru-yoshimura requested changes
@arimurashoi2000 マージ後だいぶファイルが見やすくなりました！
追加の確認をお願いします。

2023-08-09 08:54 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_show.blade.php
> +                            <div class="col-md-12 col-12"></div>
タグ未実装ですね。

2023-08-09 08:54 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_show.blade.php
> +                    <div class="card-body px-5 py-3">
余白がデザインとあってませんね。上の幅は狭すぎかな。
<img width="1470" alt="image" src="https://github.com/arimurashoi2000/newestKita/assets/108510903/db2a75c0-94c4-42e0-80bb-f1465afedd08">

2023-08-09 08:54 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +                return redirect()->route('articles.show')->with('error', '他人の記事は編集できません。');
このロジック落ちますね。テストしましたか？
修正した行毎に動作は保証しましょう。

2023-08-09 23:10 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles_show.blade.php
> +                            <div class="col-md-12 col-12"></div>
すみません。忘れていました。
記事一覧画像にもタグ表示を追加していなかったので追加しました。
お手隙の際に確認をよろしくお願いいたします。

2023-08-09 23:13 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles_show.blade.php
> +                    <div class="card-body px-5 py-3">
余白を調整しました。
確認をよろしくお願いいたします。

2023-08-09 23:33 UTC, arimurashoi2000 commented on apps/kita/app/Http/Controllers/ArticlesController.php
> +                return redirect()->route('articles.show')->with('error', '他人の記事は編集できません。');
申し訳ございません。
プルリク前に動作確認はしたのですが、ビューに自分の書いた記事じゃないとボタンを表示しないという処理を書いていたため、忘れていました。
ビューの処理をはずした状態で再度テストしたところ正常に動作したため、お手隙の際に確認をよろしくお願いいたします。

2023-08-10 00:32 UTC, hikaru-yoshimura requested changes
@arimurashoi2000 編集に対する修正ではないですけど、ラストに追加でお願いします。

あと、フラッシュメッセージにSuccess! とか Fail! の文言が抜けてました。
<img width="524" alt="image" src="https://github.com/arimurashoi2000/newestKita/assets/108510903/79f13ac0-eef2-4a86-9015-950bead3f542">

2023-08-10 00:32 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/index.blade.php
>                              </div>
border-bottomが消えてるし、投稿日下の余白が広いですかね。
あえて言うならタグの高さも大きい。
設計されたデザインにこだわりましょう。
<img width="1213" alt="image" src="https://github.com/arimurashoi2000/newestKita/assets/108510903/e66599a0-b2e4-4db8-943f-4e05943c82ec">

2023-08-10 03:09 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/index.blade.php
>                              </div>
承知しました。調整したのでお手隙の際に確認していただけると嬉しいです。
よろしくお願いいたします。
<img width="1728" alt="スクリーンショット 2023-08-10 12 07 40" src="https://github.com/arimurashoi2000/newestKita/assets/126123174/3a23eee9-90a7-4d9c-a170-d87d855d4622">

2023-08-10 03:47 UTC, merged