コメント表示、投稿機能のレビュー依頼
arimurashoi2000/newestKita pull request #9
Opened 2023-08-02 06:46 UTC by arimurashoi2000

概要
記事詳細表示機能が完成したので、お手隙の際に確認をよろしくお願いいたします。
削除ボタンは実装後に行います。
編集ボタンを押した後編集ページに移動しますが、デザインは編集機能マージ後に反映されます。

受け入れ基準

**一覧表示**
各記事表示画面の下部にその記事に対するコメント一覧を表示すること
1記事に対して複数のコメントを持てるようになっていること
コメント一覧画面は以下の項目を表示する
・投稿者名
・投稿日時
・コメント内容

**記事作成**
1記事に対して複数のコメントが投稿可能
コメントは記事詳細画面から投稿できる
コメント登録画面は以下の項目が必須
・コメント入力欄
・投稿ボタン
コメントのバリデーションチェック
文字数制限が存在していること
コメントの投稿ボタンを押した時、コメントした記事詳細画面にコメントが表示されること

関連チケット
url: https://fullspeed.atlassian.net/browse/WVQS-36

具体的な変更点
・article、commentコントローラーに処理を記載
・詳細用のビュー画面にコメント一覧と作成フォームを追加
・ルーティングの設定

機能動画

https://github.com/arimurashoi2000/newestKita/assets/126123174/d921f1a5-282f-4524-8542-5717aedc1d50
<img width="1728" alt="スクリーンショット 2023-08-02 15 31 33" src="https://github.com/arimurashoi2000/newestKita/assets/126123174/998f068c-7bd3-460d-987b-cbd7cb808dea">

2023-08-10 08:34 UTC, hikaru-yoshimura requested changes
@arimurashoi2000 大分、精度があがってきましたね！
対応お願いします！

2023-08-10 08:34 UTC, hikaru-yoshimura commented on apps/kita/resources/views/articles/articles_show.blade.php
> +<body>
A
<body>
 っていりますかね？

2023-08-10 08:34 UTC, hikaru-yoshimura commented on apps/kita/routes/web.php
> +Route::post('/comments', [CommentsController::class, 'store'])->name('comments.store')->middleware('auth');
ただのコメントで、これは直さなくてもいいです。
コメント系機能が今後増える見込みがないなら、ArticleControllerに入れるのも手。
ただ、今後コメントの削除や管理者承認などの機能は容易に考えられるので、コントローラー分けるのはGood。

2023-08-10 08:34 UTC, hikaru-yoshimura commented on apps/kita/app/Models/Article_comment.php
> +class Article_comment extends Model
Article_tagの方も指摘が漏れてましたが、Laravelのお作法的にArticleCommentやArticleTagが正しいモデル名ではないでしょうか？

2023-08-10 08:34 UTC, hikaru-yoshimura commented on apps/kita/app/Http/Controllers/CommentsController.php
> +            'contents' => 'string|required|max:100',
せっかくDBの型はTextなので、max100は少ないと思いました。
100にするならVarcharでいいじゃんてなりますね。

2023-08-10 08:59 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles_show.blade.php
> +<body>
bodyはいらないので削除しておきました。
pullしてきた時に以前のものが残らないようにきちんと確認します。

2023-08-10 09:00 UTC, arimurashoi2000 commented on apps/kita/routes/web.php
> +Route::post('/comments', [CommentsController::class, 'store'])->name('comments.store')->middleware('auth');
承知しました。自分もなんかこれ入れれそうだなあとさっき見ていて感じたので入れる方法も考えてみます。

2023-08-10 09:02 UTC, arimurashoi2000 commented on apps/kita/app/Models/Article_comment.php
> +class Article_comment extends Model
すみません。修正しました。
そういったルールをなんとなくでしか把握していなかったので、他にも開発の基本的なルールなどを調べてみます。
もしおすすめの記事などをご存知でしたらお手隙の際に教えていただけると嬉しいです。

2023-08-14 05:04 UTC, miokanedaC requested changes
@arimurashoi2000 
コメントしました。確認お願いします。

1. ヘッダー箇所の改修チケット作成お願いします。
ログインしていなくてもログアウトがヘッダーにあるのは少し違和感があるので別でチケットをきって改修お願いします。依存関係が無いと思うので、developmentsから新しくブランチを切って対応しPR作成お願いします。

2. class変更が反映されてなさそうなので、再度確認お願いします。
 php artisan migrate:refresh --seed

3. その他コメント書きました。

2023-08-14 05:04 UTC, miokanedaC commented on apps/kita/resources/views/articles/articles_show.blade.php
> +                                        <p>{{$comment->contents}}</p>
改行をいれてコメントを書いても一覧のところで改行ができていないので、改行できるようにしたほうがいいと思います。textareaを使う場合 (text型の場合) 表示も改行コードを考慮したほうがいいかなと思います。

2023-08-14 06:45 UTC, arimurashoi2000 commented on apps/kita/resources/views/articles/articles_show.blade.php
> +                                        <p>{{$comment->contents}}</p>
承知しました！修正してこのように表示されるようになりました。
<img width="1728" alt="スクリーンショット 2023-08-14 15 44 15" src="https://github.com/arimurashoi2000/newestKita/assets/126123174/1fc7839e-6481-4edb-adbd-ac87a94fec24">

2023-08-14 07:59 UTC, miokanedaC approved these changes
こちらの修正は問題なさそうです。

2023-08-14 23:16 UTC, merged